# Generated by Django 4.1.10 on 2023-10-16 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['date_added'],
            },
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Hilo',
            fields=[
                ('idTiphilo', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='Id Hilo')),
                ('nombreHilo', models.CharField(max_length=50, verbose_name='Nombre hilo')),
            ],
        ),
        migrations.CreateModel(
            name='Horarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horas', models.CharField(choices=[('08:00AM⛅', '08:00AM⛅'), ('09:00AM⛅', '09:00AM⛅'), ('10:00AM⛅', '10:00AM⛅'), ('11:00AM⛅', '11:00AM⛅'), ('12:00PM☀️', '12:00PM☀️'), ('13:00PM☀️', '13:00PM☀️'), ('14:00PM☀️', '14:00PM☀️'), ('15:00PM☀️', '15:00PM☀️'), ('16:00PM☀️', '16:00PM☀️'), ('17:00PM🌄', '17:00PM🌄'), ('18:00PM🌄', '18:00PM🌄'), ('19:00PM🌄', '19:00PM🌄')], max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('rut', models.CharField(max_length=12, primary_key=True, serialize=False, unique=True, verbose_name='Rut_usuario')),
                ('nombre', models.CharField(max_length=20, verbose_name='Nombre_usuario')),
                ('apellido', models.CharField(max_length=20, verbose_name='Apellido_usuario')),
                ('fechaNac', models.DateField(max_length=10, verbose_name='Nacimiento_usuario')),
                ('correo', models.EmailField(max_length=50, verbose_name='Correo_usuario')),
                ('telefono', models.CharField(max_length=12, verbose_name='telefono_psicologo')),
                ('contrasena', models.CharField(max_length=36, verbose_name='Contrasena_usuario')),
                ('consulta', models.ManyToManyField(blank=True, to='core.agenda')),
            ],
        ),
        migrations.CreateModel(
            name='Tipousuario',
            fields=[
                ('idTipoUsuario', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='Id_tipo_usuario')),
                ('tipoUsuario', models.CharField(max_length=50, verbose_name='Tipo_usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Psicologo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('rut', models.CharField(max_length=30, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=17)),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.especialidad', verbose_name='Especialidad')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('idPost', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='Id Post')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('intro', models.TextField()),
                ('body', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.persona')),
                ('hilo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.hilo')),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
        migrations.AddField(
            model_name='persona',
            name='tipousuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tipousuario'),
        ),
        migrations.AddField(
            model_name='persona',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('leida', models.BooleanField(default=False)),
                ('comentario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='core.comment')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.persona')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.persona'),
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.post'),
        ),
        migrations.AddField(
            model_name='agenda',
            name='horarios',
            field=models.ManyToManyField(to='core.horarios'),
        ),
        migrations.AddField(
            model_name='agenda',
            name='psicologo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.psicologo', verbose_name='Psicologo Especialista'),
        ),
    ]
