# Generated by Django 4.1.10 on 2023-12-14 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_notificacionsuperusuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agenda',
            old_name='data',
            new_name='fecha',
        ),
    ]
