# Generated by Django 4.1.10 on 2023-12-14 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_data_agenda_fecha'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agenda',
            old_name='fecha',
            new_name='data',
        ),
    ]
